name: Build Images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose --profile auto build --progress plain
      - name: DockerHub Login
        uses: docker/login-action@v3.0.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISRRY_USERNAME }}
          password: ${{ secrets.REGISRRY_PASSWORD }}
      - name: Push Image
        run: docker push registry.cn-hangzhou.aliyuncs.com/mj-mirror/stable-diffusion-webui:78
